In [11]:
!pip install jovian --upgrade -q


In [12]:
import jovian


In [13]:
jovian.commit(project='numpy-array-operations')


<IPython.core.display.Javascript object>

[jovian] Creating a new project "sumairalishahani1/numpy-array-operations"
[jovian] Committed successfully! https://jovian.ai/sumairalishahani1/numpy-array-operations


'https://jovian.ai/sumairalishahani1/numpy-array-operations'

In [14]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.mean()
function2 = np.max()
function3 = np.median()
function4 = np.cumsum()
function5 = np.argmax()

# Function 1 - np.mean()

In [18]:
# Example 1 - working
arr1=np.array([1,2,3,4,5])
var1=arr1.mean()
print('the mean of given array is ',var1)

the mean of given array is  3.0


# now  calculate mean of two dimensions along axes 

In [24]:
# Example 2 - working
arr1=[[9,8,7],[4,5,6]]
var1=np.mean(arr1,axis=0)
print(var1)

[6.5 6.5 6.5]


# now i want to calaculate the mean of any alphabets

In [26]:
# Example 3 - breaking 
arr1=['s','u','m','a','i','r']
var1=np.mean(arr1)
print(var1)

TypeError: cannot perform reduce with flexible type

In [27]:
jovian.commit()


<IPython.core.display.Javascript object>

[jovian] Updating notebook "sumairalishahani1/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/sumairalishahani1/numpy-array-operations


'https://jovian.ai/sumairalishahani1/numpy-array-operations'

# Function2 = np.max()


In [ ]:
the max function is used to find the maximum element in an given array 

In [31]:
# Example 1 - working

arr1=np.array([20,2,21,99,101])
var1=arr1.max()
print('the maximum value in given array is ',var1)

the maximum value in given array is  101


In [ ]:
we can use max function in 2d array to find out the maximum number and also on which axis

In [34]:
# Example 2 - working

arr2=[[2,3,4],[5,1,2]]
var1=np.max(arr2,axis=0)
print(var1)

[5 3 4]


In [35]:
# Example 3 - breaking
arr=np.array(['s','u','m','a','i','r'])
arr.max()


TypeError: cannot perform reduce with flexible type

In [ ]:
the max function can not apply to any alphabets or symbol it is only use for numeric values

In [36]:
jovian.commit()


<IPython.core.display.Javascript object>

[jovian] Updating notebook "sumairalishahani1/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/sumairalishahani1/numpy-array-operations


'https://jovian.ai/sumairalishahani1/numpy-array-operations'

# Function3 = np.median()


In [ ]:
the median function is use to find the average but it is used when we 
add outlier(means the value which is different from the previous values  ) 
to dataset then median to use 



In [39]:
# Example 1 - working
arr1=[1,2,3,4,5,100]
var1=np.median(arr1)
print('the median of the above array is ',var1)


the median of the above array is  3.5


In [ ]:
Calculate the median of a 2-D array along axis 1


In [40]:
# Example 2 - working

data = [[1, 2, 3], [4, 5, 6]]
median = np.median(data, axis=1)
print(median) 

[2. 5.]


In [41]:
# Example 3 - breaking (to illustrate when it breaks)
# Generate some random data
data = np.random.randn(10)

# Intentionally cause an error by trying to compute the median of a string
try:
    median = np.median(data.astype(str))
except TypeError as e:
    print("An error occurred:", e)

An error occurred: cannot perform reduce with flexible type


In [ ]:
To fix this error, we need to make sure that we are passing an array of numerical values to the median function, rather than an array of strings. One way to do this is to remove the call to astype(str), which will allow the median function to operate on the numerical data as expected.



In [42]:
jovian.commit()


<IPython.core.display.Javascript object>

[jovian] Updating notebook "sumairalishahani1/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/sumairalishahani1/numpy-array-operations


'https://jovian.ai/sumairalishahani1/numpy-array-operations'

# Function4 = np.cumsum()

In [44]:
the cumsum function is used to find out the series of number to adding their next like fabonacci series and 
returns the data type


In [45]:
# Example 1 - working

var1=np.array([0,1,2,3,4])
var1.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

# it can also be used in two dimension with axis

In [46]:
# Example 2 - working

var1 = [[1, 2, 3], [4, 5, 6]]
var2=np.cumsum(var1,axis=1)
print(var2)

[[ 1  3  6]
 [ 4  9 15]]


In [ ]:
now i am given a array with extra column in two dimension 

In [47]:
# Example 3 - breaking
var1 = [[1, 2, 3], [4, 5, 6,3]]
var2=np.cumsum(var1,axis=1)
print(var2)


C:\Users\Sumair Ali\anaconda3\python\lib\site-packages\numpy\core\fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
to fix this we need to provide a equal elements in array 

In [48]:
jovian.commit()


<IPython.core.display.Javascript object>

[jovian] Updating notebook "sumairalishahani1/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/sumairalishahani1/numpy-array-operations


'https://jovian.ai/sumairalishahani1/numpy-array-operations'

# Function5 = np.argmax()

In [ ]:
argmax() function is used to return the index of given array in any dimension

In [49]:
# Example 1 - working
var1=np.array([0,1,2,3,4])
var1.argmax()

4

In [ ]:
it can be used along the any axis

In [50]:
# Example 2 - working
var1 = [[1, 2, 3], [4, 5, 6]]
var2=np.argmax(var1,axis=0)
print(var2)

[1 1 1]


In [51]:
jovian.commit()


<IPython.core.display.Javascript object>

[jovian] Updating notebook "sumairalishahani1/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/sumairalishahani1/numpy-array-operations


'https://jovian.ai/sumairalishahani1/numpy-array-operations'